### ISSUE TITLE
Translation for persian language farsi

### ISSUE THREAD

**Issue by wikiccu** [odirleiborgert/rocket-cms#112]
Hello
I would ask you is there any plan for translation to the Persian/farsi language ?

**Comment by odirleiborgert** [comment]
Hello @wikiccu ,
I have no plans to translate to other languages.

**Comment by wikiccu** [comment]
Thank you 
so PR for translation will be rejected?

**Comment by odirleiborgert** [comment]
It will not be rejected,
I will analyze the PR and do the Merge if everything is OK
