### ISSUE TITLE
Folha de estilos

### ISSUE THREAD

**Issue by gusilveiramp** [odirleiborgert/rocket-cms#23]
Odirlei, primeiramente gostaria de parabeniza-lo pelo excelente trabalho. O painel está ficando muito bom e já estou utilizando em um projeto.

Minha dúvida é referente ao **app.css**. Percebi que existem diversas regras de estilo definidas que ainda não foram utilizadas no projeto. Como a folha de estilo é bem extensa, estou tendo dificuldade para verificar se algum elemento já existe ou se é preciso que eu crie-o. Por exemplo, eu gostaria de implementar um menu lateral responsivo na direita, entre outras coisas, mas não sei se já existem no app.css, e como css não é meu forte e a folha é bem longa, estou apanhando um pouquinho nessa busca. rsrs

Portanto, **gostaria de saber se existe alguma página de demonstração com exemplos do tema utilizado**. Caso você esteja utilizando algum tema de terceiros, poderia me indicar o site para que eu explore mais um pouco? Caso não exista, sem problemas. O projeto todo está excelente, independente disso. 

Desde já, agradeço muito pelo trabalho e atenção.

**Comment by odirleiborgert** [comment]
Olá @gusilveiramp 

Fico muito feliz por receber seu feedback. 

Eu aconselho a utilizar o LESS para trabalhar seus estilos do CMS, ainda falta eu documentar essa parte melhor, mas com o tempo pretendo criar toda essa parte.
Verifique em /resources/assets/less/, dentro desta pasta você vai encontrar o app.less que será compilado para o app.css, e dentro da pasta _inc/ terá seus includes do LESS.

O pouco de documentação que fala sobre os assets estão no link abaixo, você pode rodar o comando 'gulp watch' para verificar quando ocorrer uma alteração em algum arquivo less para ele recompilar e gerar o app.css
https://github.com/odirleiborgert/rocket-cms/blob/master/docs/pt-br/usage.md#assets

Ref. ao tema completo você pode baixar este aqui:
https://github.com/odirleiborgert/inspinia-master

Espero ter ajudado, e vai deixando feedbacks, que é com isso que vamos melhorando o Rocket CMS.

Qualquer dúvida posta ai...

**Comment by gusilveiramp** [comment]
Opa, tá ótimo! Já ajuda demais!
E quanto ao LESS, obrigado pela dica, farei isso.
