### ISSUE TITLE
Create helper to format dates in other languages

### ISSUE THREAD

**Issue by odirleiborgert** [odirleiborgert/rocket-cms#25]
**Columns**

> created_at
> updated_at
> publish_at

**Comment by denour** [comment]
What is the status of this? Maybe if is diffForHumans should be better?

**Comment by odirleiborgert** [comment]
@denour Is pending the issue, you want to work on it?
To be diffForHumans with Carbon?
https://github.com/briannesbitt/Carbon
It seems to be a good solution

**Comment by denour** [comment]
Yeah I can work in it.
