### ISSUE TITLE
Routing System and Pages

### ISSUE THREAD

**Issue by denour** [odirleiborgert/rocket-cms#33]
@odirleiborgert can you check my [fork](https://github.com/denour/rocket-cms) and tell me what do you think about the pages and if this is the idea of pages in rocket cms

**Comment by odirleiborgert** [comment]
Hello @denour , I have not had a free time to see her pull request, but promise will try to see as soon as possible.

**Comment by odirleiborgert** [comment]
PHP Parse error:  syntax error, unexpected 'require' (T_REQUIRE), expecting iden                                                                                        tifier (T_STRING) in /var/www/public/rocket-cms-denour/app/Http/Routes/Routing.p                                                                                        hp on line 45

                                                                                                                                                                        
  [Symfony\Component\Debug\Exception\FatalErrorException]                                                                                                               
  syntax error, unexpected 'require' (T_REQUIRE), expecting identifier (T_STRING                                                                                        )
                                                                                                                                                                        

Script php artisan optimize handling the post-install-cmd event returned with an                                                                                         error



  [RuntimeException]
  Error Output: PHP Parse error:  syntax error, unexpected 'require' (T_REQUI
  RE), expecting identifier (T_STRING) in /var/www/public/rocket-cms-denour/a
  pp/Http/Routes/Routing.php on line 45

**Comment by denour** [comment]
The problem is with the name of the function i had change the name and make a push then you cand pull again.

**Comment by odirleiborgert** [comment]
Hello @denour 

Sorry for the delay in answering, but was a lot of work in recent days.

Now I could analyze the fork and just missed a route `http://localhost:8000/admin` to access the CMS, is to make this route? Dai can now send the pull request for me to do the merge.

**Comment by denour** [comment]
I generate a Routing class that implements the admin and pages of the CMS this way when u are in the admin pages u can view the page. If you want I can explain to you.
