### ISSUE TITLE
Multi Idiomas

### ISSUE THREAD

**Issue by odirleiborgert** [odirleiborgert/rocket-cms#6]
Trabalhar para que o CMS e os dados possam ser em outros idiomas.

**Comment by wilsonnovaes00** [comment]
Posso ajudar nesse quesito. Quais idiomas quer começar inglês, espanhol???

**Comment by wilsonnovaes00** [comment]
Estou tentando instalar a aplicação porém me retorna um erro

> The "/home/usuario/Área de trabalho/rocket-cms/app/Http\Routes\Admin" directory does not exist.

**Comment by odirleiborgert** [comment]
Opa, show de bola @wilsonnovaes00 
Estava pensando de inicio em inglês, mas se tiver conhecimento em espanhol também seria uma boa...

**Comment by wilsonnovaes00** [comment]
@odirleiborgert Beleza, então vou começar com o inglês e depois o Espanhol e por fim o Árabe. ok?

**Comment by odirleiborgert** [comment]
Show @wilsonnovaes00 obrigado por contribuir!
